project_id = "qqbulzzezbcwstrhfbco"
[auth.jwt]
enable = true

[functions]
[functions.analyze-job-extension]
verify_jwt = true

[api]
enabled_apis = ["rest", "graphql", "realtime", "storage"]
port = 54321
schemas = ["public", "storage", "graphql_public"]